# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94787a8135eba3edef740f4c8a6304021fc6a7aecdcb6beffa61db7fe0c893a574c02367529e27e4fd59e7e3c8f75f5e945f038061b322692bd9af6055ab8966

test:
  secret_key_base: f549841557cf8749f37cd714981078f1b83db6a2109c2e641a86e4c111671f63563522ff2eb6d1ca1eda7676073a449c6d60cb0f7a31bcf4cc6a20fcc267aa3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
